name: CD Imagen docker - despliegue k8s

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      -
        name: Login en ACR
        uses: docker/login-action@v2
        with:
          registry: mvgomezcicd.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
            
      - run: |
          docker build . -t mvgomezcicd.azurecr.io/devopsfinal:${{ github.sha }}
          docker push mvgomezcicd.azurecr.io/devopsfinal:${{ github.sha }}
        
      # Operaciones kubernetes.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: mvgomezkube
          resource-group: clasedevops

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: mvgomezcicd.azurecr.io
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            mvgomezcicd.azurecr.io/devopsfinal:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret
